// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phmywmbqvaforkjohoza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBobXl3bWJxdmFmb3Jram9ob3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDIxMTcsImV4cCI6MjA3MDkxODExN30.zgLnKWW2i1dLO8VfPuaYOw0RmIBe4iK6juHcTapUE6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});